version: '3'

networks:
  influxdb-telegraf-net:
    driver: bridge

volumes:
  influxdb2:

services:
  mariadb: 
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/sql
    environment:
      - MYSQL_ROOT_PASSWORD=AdhocAdmin
      - MYSQL_DATABASE=Adhoc

  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /influx/anaisdotis-georgiou/temp/influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance. 
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - /influx/anaisdotis-georgiou/temp/influxdb2:/var/lib/influxdb2:rw
      - ${PWD}./ssl/influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:rw
      - ${PWD}./ssl/influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:rw
    environment: 
      # Use these same configurations parameters in your telegraf configuration, mytelegraf.conf.
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=Adhoc
      - DOCKER_INFLUXDB_INIT_PASSWORD=AdhocAdmin
      - DOCKER_INFLUXDB_INIT_ORG=Chualalongkorn
      - DOCKER_INFLUXDB_INIT_BUCKET=Car_info
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=AdminToken
      - INFLUXD_TLS_CERT=/etc/ssl/influxdb-selfsigned.crt
      - INFLUXD_TLS_KEY=/etc/ssl/influxdb-selfsigned.key
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    depends_on:
      - influxdb
  telegraf:
    image: telegraf
    links:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ${PWD}./telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - ./influxv2.env
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    depends_on:
      - influxdb_cli