version: '3.9'

services:
  mariadb: 
   image: mariadb:10.9
   ports:
     - 3306:3306
   volumes:
     - ~/apps/mariadb:/var/lib/sql
   environment:
    - MYSQL_ROOT_PASSWORD=AdhocAdmin
    - MYSQL_DATABASE=Adhoc