version: "3"

services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/sql
      - ./schema:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_MARIADB_DATABASE}
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb2
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

volumes:
  influxdb-storage:
