version: '3'

networks:
  influxdb-telegraf-net:
    driver: bridge

volumes:
  influxdb2:

services:
  mariadb: 
    image: mariadb:latest
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/sql
    environment:
      - MYSQL_ROOT_PASSWORD=AdhocAdmin
      - MYSQL_DATABASE=Adhoc

  influxdb:
    image: influxdb:latest
    container_name: influxdb2
    volumes:
      - ../influx/data:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    ports:
      - 8086:8086
    restart: unless-stopped

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:
      #  Sync timezone with host
      - /etc/localtime:/etc/localtime:ro
      #  Map Telegraf configuration file
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      #  Map /tmp to permanent storage  (this includes /tmp/metrics.out)
      - ../telegraf/outputs:/tmp:rw
    restart: unless-stopped
    depends_on:
      - influxdb
