import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ContainerProvider } from '../containers/containerProvider';
import Head from 'next/head';
import Layout from '../components/Layout';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ContainerProvider>
      <Head>
        <title>V2V system</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="stylesheet" href="../public/libraries/fontawesome-free-5.11.2-web/css/all.min.css"/> */}
      </Head>
      <Layout heading='V2V Communication Dashboard'>
        <Component {...pageProps} />
      </Layout>
    </ContainerProvider>
    );
}

export default MyApp
